###
GET http://localhost:3000/user/600889a4f705595398cd7442 HTTP/1.1

###
GET http://localhost:3000/thread HTTP/1.1


### 
POST http://localhost:3000/user/600889a4f705595398cd7442/tweet
content-type : application/json

{"text" : "üç"}

###
POST http://localhost:3000/user/create HTTP/1.1
content-type : application/json

{"name" : "veysel", "username" : "veyxsel", "age" : 20}

###
POST http://localhost:3000/user/600889b7f705595398cd7443/follow HTTP/1.1
content-type : application/json

{"otherId" : "600911ea91e69030ec593347"}

###
POST http://localhost:3000/user/60191f64491eb2774c2ec542/like HTTP/1.1
content-type : application/json

{ "tweetId" : "60192797ca2c375c10ad99cb"}

###
DELETE http://localhost:3000/user/600442068fef7b4808ae4449/delete HTTP/1.1


###

PATCH http://localhost:3000/user/6007507b6c495b496c8d1734 HTTP/1.1
content-type: application/json

{"name" : "degstir"}